# 端口号
server:
  port: 8222
  # 服务名称
spring:
  application:
    name: service-gateway
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 10.220.50.171:8848
  #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/**
#          filters:
#            - StripPrefix=1
        - id: service-test
          uri: lb://service-test
          predicates:
            - Path=/test/**
#          filters:
#            - StripPrefix=1